apiVersion: 1

datasources:
  - name: Postgres
    uid: postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: tinvest
    isDefault: true
    editable: false
    jsonData:
      database: tinvest
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
      connMaxLifetime: 14400
      maxOpenConns: 25
      maxIdleConns: 5
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
